name: Init
description: Init
runs:
    using: composite
    steps:
        - name: Init NodeJS
          uses: actions/setup-node@v3
          with:
              node-version: '14.21.3'
              cache: 'npm'
        - name: Install Packages
          run: npm i
          shell: bash
