name: PR
on:
    pull_request:
        branches: ['*']
jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: valitydev/action-frontend/setup@v0.1
            - run: npm ci
            - name: Build
              run: npm run build
            - uses: valitydev/action-frontend/publish@v0.1
              with:
                npm-token: ${{ secrets.NPM_TOKEN }}
